Fixing a str vs unicode issue with M.cusp_info that broke format_name in the browser with python 2.7.
The failure was reported but not caught by appveyor:

C:\Python27-x64\lib\site-packages\snappy-2.7.1a1-py2.7-win-amd64.egg\snappy\pari.py:6: UserWarning: Module snappy was already imported from C:\Python27-x64\lib\site-packages\snappy-2.7.1a1-py2.7-win-amd64.egg\snappy\__init__.pyc, but c:\projects\snappy-ss8g2 is being added to sys.path
  from pkg_resources import parse_version
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27-x64\lib\lib-tk\Tkinter.py", line 1547, in __call__
    return self.func(*args)
  File "C:\Python27-x64\lib\site-packages\snappy-2.7.1a1-py2.7-win-amd64.egg\snappy\browser.py", line 489, in update_current_tab
    self.update_invariants()
  File "C:\Python27-x64\lib\site-packages\snappy-2.7.1a1-py2.7-win-amd64.egg\snappy\browser.py", line 535, in update_invariants
    self.update_aka()
  File "C:\Python27-x64\lib\site-packages\snappy-2.7.1a1-py2.7-win-amd64.egg\snappy\browser.py", line 579, in update_aka
    mflds['weak'] = [format_name(N) for N in M.identify()]
  File "C:\Python27-x64\lib\site-packages\snappy-2.7.1a1-py2.7-win-amd64.egg\snappy\browser.py", line 576, in format_name
    if all(N.cusp_info('is_complete')):
  File "cython\core/manifold.pyx", line 1121, in SnapPy.Manifold.cusp_info
    cusp_index = valid_index(
  File "cython\core/basic.pyx", line 82, in SnapPy.valid_index
    return xrange(n)[i]
TypeError: 'unicode' object cannot be interpreted as an index