Removing Python 3.4 from Appveyor as one of the packages that SnapPy depends on (colorama) explicitly does not work on Python 3.4 anymore.
Collecting colorama; sys_platform == "win32" (from IPython)
  Downloading https://files.pythonhosted.org/packages/31/cb/88c908c1be067fb6bacd3d7488ccab1a212533767b951933aac3d22648e2/colorama-0.4.2-py2.py3-none-any.whl
ERROR: colorama requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.4